// export const CREATE_COURSE = "CREATE_COURSE";
export const LOAD_COMPANIES_SUCCESS = "LOAD_COMPANIES_SUCCESS";
export const LOAD_BUILDINGS_SUCCESS = "LOAD_BUILDINGS_SUCCESS";
export const LOAD_APARTMENTS_SUCCESS = "LOAD_APARTMENTS_SUCCESS";
export const LOAD_ROOMMATEGROUPS_SUCCESS = "LOAD_ROOMMATEGROUPS_SUCCESS";
export const LOAD_PROSPECTS_SUCCESS = "LOAD_PROSPECTS_SUCCESS";
